### PR TITLE
Artifact equipment fix 1

### PR DESCRIPTION
**Pull request by Blogaugis**
Makes some gear equipment have bit better master crafted and artifact stats.

### CODE REVIEW

**Comment by EttyKitty** [comment]
> Makes some gear equipment have bit better master crafted and artifact stats.

Why should all of these items give damage resistance? Imo that's a bit arcady.
Servo arms are just prosthetics and don't offer any targeting help or damage protection. Neither does the narthecium.
One can argue that servo-arms may add a bit hp, but just a tiny bit.
Psychic hood also should only offer protection against enemy psy attacks.

Also, damage resistance overall is a very strong stat that you should use carefully.

**Comment by Blogaugis** [comment]
> Why should all of these items give damage resistance? Imo that's a bit arcady.

I figured that damage resistance was the most basic kind of option, to at least make master crafting and using these gear items worthwhile (instead of gifting to other factions).
In my own fork, I went with much more freedom, like giving them AC as well.
> Servo arms are just prosthetics and don't offer any targeting help or damage protection.

I was under impression that servo arms would have various integrated tools in them (like, 40k's equivalent of contemporary mechanic's toolkit, which means they should be able to tell things like tire pressure from afar, especially since it is Master Crafted or even artifact items).
Lastly, I think they could serve as damage sponges - you put this servo arm between you and a projectile traveling at you - the projectile hits the servo arm, instead of other important parts/organs.

> Neither does the narthecium.

Similarly to the techmarine earlier, the doctor equipment of 40k could be something incredibly powerful in terms of identifying weakpoints in a biological foe. But, I guess it is a bit harder with narthecium.
> Psychic hood also should only offer protection against enemy psy attacks.

Well, these are **Master Crafted** and **Artifact** tier equipment, that are not-so-easy to acquire, or create.
I think any expert crafter would try their best to ensure that their made equipment can raise protection or other capabilities of the wearer, that's what Master Crafted and other high quality items should be about, shouldn't they?
In a way, artifact tier equipment may as well be reality-bending relics from the 30k and earlier, like DAoT.

> Also, damage resistance overall is a very strong stat that you should use carefully.

Fair. So what could be other options?
I don't really like straight up buffing HP, as it tends to make start of game rather messy. I'd prefer if the equipment raises the constitution or other marine stats.
I suppose adding a tiny bit of AC can be an option (armour stat used on armours), if You think this being a better option.
Let me know if you have any ideas.
Either way, let me know if I should try reworking it, or just close this.

**Comment by EttyKitty** [comment]
> Fair. So what could be other options?
If I'm being honest, personally, I would rather remove quality possibility from these items altogether.
If not:
- Narthecium - can get more charges to save more marines per battle and/or regen more hp to saved ones.
- Psychic Hood - more perils protection, more psy attack resist (I don't think they exist tho).
- Servo Arms - more vehicle repair charges per battle.

If the argument is, that these are harder to implement - yes, but damage resistance is too strong.
Before anyone bothers with the harder options, I'm okay with the damage resistance if you lower values on both servo-arms by 5% across all qualities.

**Comment by EttyKitty** [comment]
But, you can in fact always reach out to other people in community or just bypass me and ask zab or nelsonh, as I'll not bodyblock this. I'm just stating *my* personal opinion.

**Comment by Blogaugis** [comment]
> If the argument is, that these are harder to implement - yes, but damage resistance is too strong. Before anyone bothers with the harder options, I'm okay with the damage resistance if you lower values on both servo-arms by 5% across all qualities.

Okay. I nerfed the MC and A servo arms, both types.
So, they should be at least marginally better now.

**Pull request merged**
