### PR TITLE
feat: "Generate random name" button on some creation slides

### PR DESCRIPTION
**Pull request by VanWeapon**
Could be replaced in future by a proper icon but just using "?" for now as a placeholder

### CODE REVIEW

**Review by OH296 — APPROVED** [review]
Not tested, but otherwise looks good

**Comment by EttyKitty** [comment]
I just want to test if this works and then it's good. Just need to find a moment.

**Review by EttyKitty — APPROVED** [review]
Yep, everything works. I thought it should also add a button to randomize chapter name, but oh well.

**Comment by VanWeapon** [comment]
> Yep, everything works. I thought it should also add a button to randomize chapter name, but oh well.

The random chapter name also influences the livery scheme and some extra starting attributes, all the names are hardcoded in `scr_chapter_random` which I didn't want to rewrite here

**Pull request merged**
