### PR TITLE
feat: Angry marines

### PR DESCRIPTION
**Pull request by VanWeapon**
Finish off angry marines chapter data and add their artifact weapon type.

### CODE REVIEW

**Comment by VanWeapon** [comment]
this crashes unless https://github.com/EttyKitty/ChapterMaster/pull/173 is applied as well btw

**Comment by EttyKitty** [comment]
> Finish off angry marines chapter data and add their artifact weapon type.

Wtf is the "Assault Chainfist" haha? Is that a homebrew, or does it actually exist?

**Comment by VanWeapon** [comment]
It sounds very homebrew. Literally described in the wiki as "gauntlets of ultramar but angrier". If it only exists as an artifact that's probably fine? I didn't actually check what conditions stuff shows up in the shop & forge to make sure it's excluded.

**Comment by VanWeapon** [comment]
Nevermind, of course the whole shop is hardcoded so they wont get included there. And looks like #75 wont accidentally add them either

**Comment by VanWeapon** [comment]
Also if you make this faction with the ingame editor you only end up spending 75/100 points, but I can't really think of any other advantages to give them that make sense.

**Comment by EttyKitty** [comment]
> If it only exists as an artifact that's probably fine? I didn't actually check what conditions stuff shows up in the shop & forge to make sure it's excluded.

Yes, it's 100% fine, as this is funny af. Having this "easter egg" type of stuff - when it's not intrusive, - is cool with me.

> Also if you make this faction with the ingame editor you only end up spending 75/100 points, but I can't really think of any other advantages to give them that make sense.

If you really want to bother with this, I'm fine with giving them more special items, if they have any.
Check DA's mace of absolution. Only DA can buy it.

**Pull request merged**
