### PR TITLE
fix: prevent duplicate inspection.

### PR DESCRIPTION
**Pull request by jhillacre**

### CODE REVIEW

**Comment by jhillacre** [comment]
sorry, lot's of whitespace changes in this one. if you use github's hide whitespace changes feature, the change should be clearer.

**Comment by EttyKitty** [comment]
> sorry, lot's of whitespace changes in this one. if you use github's hide whitespace changes feature, the change should be clearer.

Np at all. It should imo be enforced that we use a JS formatted on all code, because old code is unreadable without it.
Maybe just do it in two commits/prs (not in this case). Or maybe someone just should run ALL code through a formatter in one pr.

Just a note, in case you use JS one - the one I use, breaks `$"something {variable}"` syntax by doing this `$ "something {variable}`. I manually run a search and replace "$ " to "$" afterwards.
And it also doesn't like "and" and "or". It doesn't automaticly place spaces between them and if conditions. I.e. `if (condition) and(condition2)`. Doesn't happen with `&&` and `||` though.

**Review by OH296 — APPROVED** [review]
auto merge no way it can go wrong i can see. Was this tested using the "inspection" cheat?

**Comment by jhillacre** [comment]
I tested in a game where my world-based chapter was getting two inspectors, and now it gets one.

I did not test as a fleet-based chapter.

**Pull request merged**
