### PR TITLE
New Disadvs

### PR DESCRIPTION
**Pull request by KRdaMystic**
5 new disadvs
-Small Reclusiam, Apothecarion, Librarius
-Serpents Delight
-Enduring Angels
tweaks prices and metas

### CODE REVIEW

**Comment by EttyKitty** [comment]
@KRdaMystic, can you make sure that it's based on 0.10 and change target to it? I don't think we're planning to push anything new to 0.9.

I can do it as well, just let me know.

**Comment by KRdaMystic** [comment]
> @KRdaMystic, can you make sure that it's based on 0.10 and change target to it? I don't think we're planning to push anything new to 0.9.
> 
> I can do it as well, just let me know.

It should be now unless I messed something up

**Comment by OH296** [comment]
Screenshot 2024-12-16 at 12 02 51
edit the pr to be into release/0.10.0 otherwise it's trying to merge all of 0.10.0 into compile main. also then it will be a lot easier to find the actual files you changed lol

**Comment by EttyKitty** [comment]
@KRdaMystic, may I suggest splitting this PR into two? I have no real issue with the edits part of this pr, but new stuff is not as simple in my eyes.

I've split them to save your time.
you can just reset this one to [this branch](https://github.com/EttyKitty/ChapterMaster/tree/pr/new-chapter-traits).
and then create another pr from [this branch](https://github.com/EttyKitty/ChapterMaster/tree/pr/chapter-trait-edits).

**Pull request closed without merging**
