### PR TITLE
feat: Disable borderless window

### PR DESCRIPTION
**Pull request by VanWeapon**
Borderless windowed mode offers no benefits and only downsides: 
- You can't change the window location 
- Auto center is buggy 
- Can't resize window 

All of these problems go away with bordered windowed mode. 
Unfortunately, this is a compiler setting, and doesn't look like it can be changed dynamically in-game with a setting, but tbh i don't see much reason to not make this change.

### CODE REVIEW

**Comment by EttyKitty** [comment]
Overall, I agree with the stated downsides, just want to test it for some edge-cases and then ll merge.

**Comment by EttyKitty** [comment]
@VanWeapon, I briefly tested this and it seems to work fine.

As a note, does [this](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Cameras_And_Display/The_Game_Window/window_enable_borderless_fullscreen.htm) or [this](https://manual.gamemaker.io/monthly/en/GameMaker_Language/GML_Reference/Cameras_And_Display/The_Game_Window/window_set_showborder.htm) (not sure what is the difference at first glance) not work?
I still think that setting it to normal window by default is fine. Just something to keep in mind.

**Comment by VanWeapon** [comment]
I found fullscreen one, i was looking for ages to find a version of that function for windowed mode and couldn't find it, guess im just blind. That should work for creating a setting

**Comment by OH296** [comment]
What was the consensus here? just tested and it seems to work fine on my end, would it be better to hold off on this till a setting can be made just in case of unexpected annoyances wit player experience or just go for it?

**Comment by EttyKitty** [comment]
> What was the consensus here? just tested and it seems to work fine on my end, would it be better to hold off on this till a setting can be made just in case of unexpected annoyances wit player experience or just go for it?

I really want to add a checkbox into settings, but realistically I probably won't be able to do it in near time.
So unless anyone thinks that there may be any alt+tab/alt+enter issues - I'm okay with just merging it as it is.

**Pull request merged**
