### PR TITLE
fix: Several bugs with fleet combat

### PR DESCRIPTION
**Pull request by OH296**
- ships in combat did not have a built in max speed variable causing crashes with broken references
- better error handling on clean up scripts
- crash resulting from `luck` instead of `_unit.luck`

## Summary by Sourcery

Fix several bugs related to fleet combat that caused crashes.

Bug Fixes:
- Fixed a crash caused by incorrect referencing of the "luck" variable.
- Fixed a crash caused by ships not having a max speed variable.
- Improved error handling in ship cleanup scripts.

Enhancements:
- Clear vehicle variables when resetting vehicle arrays.

### CODE REVIEW

**Comment by OH296** [comment]
@sourcery-ai review

**Comment by EttyKitty** [comment]
@sourcery-ai review

**Comment by EttyKitty** [comment]
@sourcery-ai review

**Comment by OH296** [comment]
@sourcery-ai review

**Comment by EttyKitty** [comment]
@sourcery-ai review

**Pull request merged**
