### PR TITLE
player ship arrays are now fully dynamic

### PR DESCRIPTION
**Pull request by OH296**
- player ship arrays are now fully dynamic
- 0 index now used for ship arrays
- splintered disadvantage fixed
- needs testing and also priority merging due to the sheer number of scripts touched
- breaks legacy saves

### CODE REVIEW

**Comment by EttyKitty** [comment]
I'm not sure what to do with this, as it's based on compile/main but wants to merge into 0.10.

**Comment by OH296** [comment]
> I'm not sure what to do with this, as it's based on compile/main but wants to merge into 0.10.

I've now merged 10.0 in, i based off of compile/main as it was meant to be minor work, wither way i have solved conflicts so it should just have the effect of updating 10.0 with compile main once merged

**Comment by EttyKitty** [comment]
> I've now merged 10.0 in

Oh, my god. That just made the commit gore worse.
You should've waited for me to merge main into 0.10 and then rebased on top of it. Then I could've just squashed this PR and merged it.
Now I have to create a merge commit and hope that it'll not break commit history.
Nelsonh, sigh.
Can you revert/reset the merge?

Actually, let me see if I can fix this.

**Comment by OH296** [comment]
> > I've now merged 10.0 in
> 
> Oh, my god. That just made the commit gore worse. You should've waited for me to merge main into 0.10 and then rebased on top of it. Then I could've just squashed this PR and merged it. Now I have to create a merge commit and hope that it'll not break commit history. Nelsonh, sigh. Can you revert/reset the merge?
> 
> Actually, let me see if I can fix this.

There is a 0 percent chance i can revert shit, i broke a full half the game with the initial implementation of this....I can only apologise deeply for the pain caused but i was stuck in a hole from having broken so much in a single cluster fuck commit as rebasing was simply not an option when i tried due to the sheer number of conflict points

**Pull request merged**
