### PR TITLE
refactor: remove/comment unused functions, add zoom related `global.` prefix

### PR DESCRIPTION
**Pull request by jhillacre**

### CODE REVIEW

**Review by OH296 — COMMENTED** [review]
I would like to do some play testing just before i approve this just to ensure nothing goes wonky (to do with cm code base being what it is rather than any issues with the pr). Other wise i see no reasons not to merge ASAP

**Comment by EttyKitty** [comment]
Do unused function actually inflict any considerable performance impact?

I understand deleting obsolete functions, that were replaced by something new, but deleting stuff like `hold_exclusive()`, various `draw_text` helpers and `choose_weighted_range` (that are unused atm, but I created them so you can see them in autocomplete when you may need them).

I often follow the rule of writing functions for every occasion, even if unused now, and enjoy having a pre-built library of useful functions waiting for me.

**Comment by jhillacre** [comment]
Unused functions don't affect game performance, but they do add maintenance and readability costs.

Do you want to keep any of these?

**Comment by EttyKitty** [comment]
> maintenance and readability costs.

Why? I mean, when stuff is in one file - yeah, when it's flooded with functions it may be hard to navigate. But that can be solved by splitting function files and grouping them differently in each case, if needed.
And maintenance, you mean If you update one function in a group, you need to update all others? Yeah, I can see that being a bother, but eh. I'm yet to see a case where it's an actual problem.

I still think the benefit of having even too many functions pre-written and ready to be used when you require them, outweighs stated downsides. Time was spent to write them. Ideas existed only at that point of time and may not exist later (text functions are simple, so it doesn't apply to them). Autocomplete reminding you of existing functions in the library is also useful.

> Do you want to keep any of these?

As I've explained, I would love to have all functions that are not explicitly replaced by something or objectively obsolete and hence no longer needed, to stay. But that's my personal opinion.

In this case, I would like for: `choose_weighted_range`, `hold_exclusive`, `draw_text` functions to stay.
`shadow_creator` - I'm not sure how useful it is, as I've never used it, but it looks okay as well?
Distribution functions are something that I'm very not sure about, as I'm not sure how many if any of them even work properly or if that's just our tries that failed, I don't remember.
Everything else - can't say, as I don't really understand them.

**Comment by jhillacre** [comment]
Having a library of pre-written functions can be helpful. I understand it's frustrating to see recent work potentially changed. My goal in identifying unused functions is to make CM easier to navigate and debug, given the confusing nature of the current code, with implied globals and functions handling multiple object types as context. Reducing inactive code lowers the effort required to understand and work with the active parts.

On technical debt: every piece of code we keep has a maintenance cost, primarily in the ongoing effort to understand it and its role. Not all debt is negative; it's worth paying for features that make the game fun. Keeping code lean lowers the "interest" we pay on this good debt regarding complexity and upkeep. Removing truly obsolete code helps manage this debt over time.

Since I could see these were recent functions, I initially commented them out rather than deleting them. **tldr; I've now reverted these changes as of commit da6710ca**. I didn't make judgment calls about specific functions—I reviewed each one flagged by Stitch as unused, confirmed it wasn't in use, and either deleted it if it was older or commented it out if it was recent. That seemed like a good first pass for identifying obsolete code. My interpretation of what's "objectively" obsolete differs from yours, and that's why I appreciate your reviews on this PR (or any other).

**Comment by OH296** [comment]
Just so we can reach a final point of this, @EttyKitty obviously having as many functions as possible is useful so i'm not going to disagree with you but it's worth noting that as you and i have written a great volume of this code base it can be difficult for us to be objective about certain factors of how understandable or manageable the code base is and maybe end up being overprotective (defiantly one of my issues anyhow). Hopefully the current agreed position where by no functions are actually deleted unless truly obsolete can let this move forward, but if not i suggest we move this conversation to a discord thread and we can hash out where we go.

@jhillacre Thanks for making your thought process clear, it's a difficult situation as we are not a corporate and obviously i know i personally am pretty protective of any of my code or concept getting the chop or overwritten so it may be a certain amount of bloat above a normal acceptable standard gets left behind just as a part pf the projects nature. Either way i appreciate the points and it's interesting to have perspective on the legibility of the code.

**Comment by EttyKitty** [comment]
@jhillacre, I'll merge this, as I have no problems with the current state of the PR. 

Sorry if I strike as protective of my code, as in this case I don't really care for these exact text and choose functions, that were written by me. I'm also hesitant to queue some of the nelsonh's functions and would be hesitant for functions of anyone else, if I see their usefulness in the future.
I just don't want to create a precedent for the future, when functions that are marked by the IDE as “unused”, are by default placed into a queue of possible deletion unless used in 6 months. And I feel like you generally agree with this sentiment.

Yet, I wholeheartedly agree with the idea of deleting stuff that is obsolete and just clogs the codebase, and keeping the codebase lean and have less junk code.

As a closing remark:
> My interpretation of what's "objectively" obsolete differs from yours

For me, it's any function that is unused and:
- a) On practice is replaced by something else, that can fill the same functionality role but is better in some way, leaving no reason to use the old function.
	- `scr_wep_abbreviate` was replaced by struct properties, no objective reason to keep it.
- b) Is unused and at first glance has a small chance of being used in the future. 
	- `scr_special_weapon` in my eyes has no apparent use cases for the future and is not universal or complex enough to let it stay and/or try to adapt it for something else.
- c) Just doesn't look useful for some reason. Subjective, yes, but there may be cases where it's common sense.
	- Like, there is a function that does one tiny-little thing and there is no understandable reason to do it with a function.

`hold_exclusive`, as a counter example, has no alternatives, has an extreme chance of being used in the future, and generally looks useful at first glance.
`shadow_creator` may've been the same, but if @OH296 is okay with it deleted - I guess I miss the context, and it's one of the 3 reasons I listed.

p.s. I really feel bad for even attempting to lecture someone who probably has 10 folds of my coding experience, and may be objectively wrong in my views. So, sorry if I'm trying to lecture where I shouldn't.

**Comment by jhillacre** [comment]
Not to extend this PR comments too much, but with CM and GM, the experience ratio runs the other way. My original reply was short because I also don't want to come across didactic, so I hope you didn't feel lectured at in the follow up.

**Pull request merged**
