### PR TITLE
feat: Overhaul Techmarine and Apothecary systems

### PR DESCRIPTION
**Pull request by OH296**
as stated, also contains all the forge maintenance work  and apothecary point stuff

pr does a number of things

-reworks the existing apothecary_simple functions to run at the same time as the forge points

    - this allows forge points to be deducted each turn if vehicle repairs are present
    - forge points are doubled accross the board
    - forge points are also now deducted each turn depending on thte total equipment of each marine, in other words all 
    - items now have a maintenance value
    - apothecary points created as a mirror resource to forge points

- All items now have a maintenance value as has been discussed in great detail at various points

   - item maintenance values can be meddled with as much as we like

   - most use tags to define their base limits

- forge point production doubled across the board to accomodate usage

- This works to debuff and create a reason to use lower grade weaponry

- repairing vehicles now reduces forge production of tech priests undertaking repairs for the given turn

- tinkerer trait now reduces maintenance of equipment by a third

- the equipment struct has been moved to it's own script to make calculations easier

- point calculation for forge and upcoming apothecary points moved to their own script and are now managed by the SpecialistPointsHandler

- gene slaves now require incubators to be made in the forge
   - gene slave incubator batches will slowly degrade over time
   - gene slave incubator batches must be assigned to an apothecary, the batch will  be presumed to travel around with the said apothecary

Based on previous chats over the last year or so i'm happy with the mechanics being in line with what has been discussed and in line with the origional specification i had in mind when i built the forge system.
That said there is lots of room for balancing and moving of value as such this is marked as open but there is lots of room for tweaking either before or after merge

### CODE REVIEW

**Comment by EttyKitty** [comment]
isn't this #35 the same PR?

**Comment by OH296** [comment]
> isn't this #35 the same PR?

sam branch further developed, so depending on how things go depends on which branches and pull requests i'll open/close, i'll probably end up closing the old one

**Comment by OH296** [comment]
Closed all other pull requests stemming from this branch of development to centralise here

**Comment by EttyKitty** [comment]
> sam branch further developed, so depending on how things go depends on which branches and pull requests i'll open/close, i'll probably end up closing the old one

You can change the target branch after creating the PR.
Also, that PR was the same source branch just different target, so I could've just changed the target.
Are you sure that you want this merged into `compile/main` and not `release_0.10`?

**Pull request merged**
